name: Digital Presence
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-versions: [16.x]
    steps:
     - uses: actions/checkout@master
     - run: npm install
     - run: npm build
#      - run npm est
     - uses: actions/checkout@master
     - name: Upload to S3
     - run: |
          aws s3 mb s3://digital-presence.com
          env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_DEFAULT_REGION: 'us-east-1' 
            SOURCE_DIR: 'build'
      
